[tool.poetry]
name = "async-python"
version = "0.1.0"
description = ""
authors = ["SALEH846 <ranaasaleh846@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
